create table pos_transaction(
    TRAN_ID	varchar(100),
    TRANSACTION_DATE varchar(50),	
    TRANSACTION_TIME	varchar(50),	
    MERCHANT_NAME	varchar(50),
    MERCHANT_ID	varchar(50),
    TERMINAL_ID	varchar(50),
    AMOUNT	numeric(15,6),
    BIN	varchar(50),
    PAN		varchar(50),
    ACQUIRING_BANK	varchar(50),
    ISSUING_BANK	varchar(50),
    SYSTEM_RETRIEVAL_NO	varchar(50),
    RESPONSE_CODE	varchar(50),
    SYSTEM_TRACE_NO varchar(50),
    CURRENCY varchar(50),
    GROSS_AMOUNT numeric(15,6),
    NET_AMOUNT	numeric(15,6),
    RETAILER_NAME varchar(60),
    TERMINAL_OWNER varchar(260),
    FEE	varchar(50),
    CARD_NUMBER	varchar(50),	
    CUSTOMER_ACCT varchar(50),	
    STATUS	varchar(50),
    REVERSAL_ID	varchar(50),
    REMARK	varchar(50),
    TRANS_TYPE	varchar(50),
    DISTRICT	varchar(50),
    OWNER varchar(50),	
    ADDITIONAL_INFO varchar(150),
    PRIMARY KEY (TRAN_ID)
);
